name = "jamespsterling-remix-dev"
compatibility_date = "2023-08-14"

# Development build - no Sass compilation to avoid conflicts
[build]
command = "npm run build"
cwd = "."

[vars]
NODE_ENV = "development"
